server:
  port: 0
  max-http-header-size: 10MB
  servlet:
    context-path: /sae-authenticator
spring:
  application:
    name: sae-authenticator
  mvc:
    servlet:
      path: /api/v1
  profiles:
    active: dev
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com: DEBUG

    