server:
  port: 0
  max-http-header-size: 10MB
  servlet:
    context-path: /sae-authenticator
spring:
  application:
    name: sae-authenticator
  mvc:
    servlet:
      path: /api/v1
logging:
  level:
    com: DEBUG

    