server:
  port: 0
  max-http-header-size: 10MB
  servlet:
    context-path: /sae-authenticator
spring:
  application:
    name: sae-authenticator
  mvc:
    servlet:
      path: /api/v1
  profiles:
    active: dev
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: none
  datasource:
    driver:
      class: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: jdbc:sqlserver://;serverName=172.20.5.157;databaseName=SAE_NACIONALES;encrypt=false;trustServerCertificate=false;
    url: jdbc:sqlserver://;serverName=172.20.5.157;databaseName=SAE_NACIONALES;encrypt=false;trustServerCertificate=false;
    password: truper2022
    username: APP_SAEN
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        show-sql: true
logging:
  level:
    com: DEBUG
